import { Document, DocumentType, DocumentStatus } from '@/lib/types/document'

export const mockDocuments: Document[] = [
  {
    id: 'doc-001',
    clientId: 'client-001',
    type: 'passport',
    name: 'CEO Passport',
    fileName: 'john_doe_passport.pdf',
    fileSize: 2456789,
    mimeType: 'application/pdf',
    status: 'approved',
    uploadedBy: 'client-001-user',
    uploadedByName: 'John Doe',
    uploadedAt: '2025-01-05T10:30:00Z',
    reviewedBy: 'co-001',
    reviewedByName: 'Emily Rodriguez',
    reviewedAt: '2025-01-06T14:20:00Z',
    url: '/documents/mock/passport-001.pdf',
    thumbnailUrl: '/documents/mock/passport-001-thumb.jpg',
    annotations: [],
    comments: ['Passport verified. Expiry date: 2028-05-15'],
    expiryDate: '2028-05-15',
    isRequired: true,
    version: 1,
  },
  {
    id: 'doc-002',
    clientId: 'client-001',
    type: 'business_license',
    name: 'Business License',
    fileName: 'acme_corp_license.pdf',
    fileSize: 1234567,
    mimeType: 'application/pdf',
    status: 'under_review',
    uploadedBy: 'client-001-user',
    uploadedByName: 'John Doe',
    uploadedAt: '2025-01-07T11:45:00Z',
    url: '/documents/mock/license-001.pdf',
    thumbnailUrl: '/documents/mock/license-001-thumb.jpg',
    annotations: [],
    comments: [],
    expiryDate: '2026-12-31',
    isRequired: true,
    version: 1,
  },
  {
    id: 'doc-003',
    clientId: 'client-001',
    type: 'kyc_form',
    name: 'KYC Form',
    fileName: 'kyc_completed.pdf',
    fileSize: 987654,
    mimeType: 'application/pdf',
    status: 'approved',
    uploadedBy: 'client-001-user',
    uploadedByName: 'John Doe',
    uploadedAt: '2025-01-04T09:15:00Z',
    reviewedBy: 'co-001',
    reviewedByName: 'Emily Rodriguez',
    reviewedAt: '2025-01-05T10:30:00Z',
    url: '/documents/mock/kyc-001.pdf',
    thumbnailUrl: '/documents/mock/kyc-001-thumb.jpg',
    annotations: [],
    comments: ['All information verified and complete'],
    isRequired: true,
    version: 2,
    previousVersions: ['doc-003-v1'],
  },
  {
    id: 'doc-004',
    clientId: 'client-002',
    type: 'financial_statement',
    name: 'Annual Financial Statement 2024',
    fileName: 'financial_statement_2024.pdf',
    fileSize: 3456789,
    mimeType: 'application/pdf',
    status: 'approved',
    uploadedBy: 'client-002-user',
    uploadedByName: 'Jane Smith',
    uploadedAt: '2025-01-03T14:20:00Z',
    reviewedBy: 'co-002',
    reviewedByName: 'Marcus Johnson',
    reviewedAt: '2025-01-04T16:45:00Z',
    url: '/documents/mock/financial-001.pdf',
    thumbnailUrl: '/documents/mock/financial-001-thumb.jpg',
    annotations: [],
    comments: ['Financial statements reviewed and approved'],
    isRequired: true,
    version: 1,
  },
  {
    id: 'doc-005',
    clientId: 'client-002',
    type: 'proof_of_address',
    name: 'Proof of Address',
    fileName: 'utility_bill.pdf',
    fileSize: 567890,
    mimeType: 'application/pdf',
    status: 'rejected',
    uploadedBy: 'client-002-user',
    uploadedByName: 'Jane Smith',
    uploadedAt: '2025-01-08T10:00:00Z',
    reviewedBy: 'co-002',
    reviewedByName: 'Marcus Johnson',
    reviewedAt: '2025-01-09T09:30:00Z',
    url: '/documents/mock/address-001.pdf',
    thumbnailUrl: '/documents/mock/address-001-thumb.jpg',
    annotations: [],
    comments: ['Document is older than 3 months. Please provide recent utility bill or bank statement.'],
    isRequired: true,
    version: 1,
  },
  {
    id: 'doc-006',
    clientId: 'client-003',
    type: 'incorporation_certificate',
    name: 'Certificate of Incorporation',
    fileName: 'incorporation_cert.pdf',
    fileSize: 1890123,
    mimeType: 'application/pdf',
    status: 'approved',
    uploadedBy: 'client-003-user',
    uploadedByName: 'Robert Chen',
    uploadedAt: '2025-01-02T15:30:00Z',
    reviewedBy: 'co-001',
    reviewedByName: 'Emily Rodriguez',
    reviewedAt: '2025-01-03T11:15:00Z',
    url: '/documents/mock/incorporation-001.pdf',
    thumbnailUrl: '/documents/mock/incorporation-001-thumb.jpg',
    annotations: [],
    comments: ['Certificate verified'],
    isRequired: true,
    version: 1,
  },
  {
    id: 'doc-007',
    clientId: 'client-003',
    type: 'tax_return',
    name: 'Tax Return 2024',
    fileName: 'tax_return_2024.pdf',
    fileSize: 2789456,
    mimeType: 'application/pdf',
    status: 'uploaded',
    uploadedBy: 'client-003-user',
    uploadedByName: 'Robert Chen',
    uploadedAt: '2025-01-10T13:45:00Z',
    url: '/documents/mock/tax-001.pdf',
    thumbnailUrl: '/documents/mock/tax-001-thumb.jpg',
    annotations: [],
    comments: [],
    isRequired: true,
    version: 1,
  },
  {
    id: 'doc-008',
    clientId: 'client-004',
    type: 'shareholder_agreement',
    name: 'Shareholder Agreement',
    fileName: 'shareholder_agreement.pdf',
    fileSize: 3123456,
    mimeType: 'application/pdf',
    status: 'under_review',
    uploadedBy: 'client-004-user',
    uploadedByName: 'Sarah Williams',
    uploadedAt: '2025-01-09T16:20:00Z',
    url: '/documents/mock/shareholder-001.pdf',
    thumbnailUrl: '/documents/mock/shareholder-001-thumb.jpg',
    annotations: [],
    comments: [],
    isRequired: false,
    version: 1,
  },
  {
    id: 'doc-009',
    clientId: 'client-005',
    type: 'compliance_certificate',
    name: 'ISO Compliance Certificate',
    fileName: 'iso_certificate.pdf',
    fileSize: 1567890,
    mimeType: 'application/pdf',
    status: 'expired',
    uploadedBy: 'client-005-user',
    uploadedByName: 'Michael Brown',
    uploadedAt: '2024-06-15T10:00:00Z',
    reviewedBy: 'co-003',
    reviewedByName: 'David Park',
    reviewedAt: '2024-06-16T14:30:00Z',
    url: '/documents/mock/iso-001.pdf',
    thumbnailUrl: '/documents/mock/iso-001-thumb.jpg',
    annotations: [],
    comments: ['Certificate expired. Please upload renewed certificate.'],
    expiryDate: '2024-12-31',
    isRequired: true,
    version: 1,
  },
  {
    id: 'doc-010',
    clientId: 'client-006',
    type: 'passport',
    name: 'Director Passport',
    fileName: 'director_passport.pdf',
    fileSize: 2234567,
    mimeType: 'application/pdf',
    status: 'pending_upload',
    uploadedBy: '',
    uploadedByName: '',
    uploadedAt: '',
    url: '',
    annotations: [],
    comments: [],
    expiryDate: '',
    isRequired: true,
    version: 0,
  },
]

// Helper function to get required documents for a client
export function getRequiredDocumentTypes(): DocumentType[] {
  return [
    'passport',
    'business_license',
    'kyc_form',
    'proof_of_address',
    'financial_statement',
    'incorporation_certificate',
  ]
}

// Helper function to get documents by client ID
export function getDocumentsByClientId(clientId: string): Document[] {
  return mockDocuments.filter(doc => doc.clientId === clientId)
}

// Helper function to get documents by status
export function getDocumentsByStatus(status: DocumentStatus): Document[] {
  return mockDocuments.filter(doc => doc.status === status)
}

