import { Lead, Industry, PipelineStage, LeadActivity } from '@/lib/types/lead'

// Helper to generate varied timestamps for activities
function generateVariedDate(baseDate: Date, daysAgo: number, hoursOffset: number = 0): string {
  const date = new Date(baseDate)
  date.setDate(date.getDate() - daysAgo)
  date.setHours(date.getHours() + hoursOffset)
  return date.toISOString()
}

// Helper to generate mock activities with varied timestamps
function generateActivities(leadId: string, stage: PipelineStage, leadIndex: number = 0, baseDate?: Date): LeadActivity[] {
  // Use provided base date or default to realistic dates based on lead context
  const now = baseDate || new Date('2025-01-15T12:00:00Z') // Reference date
  const dayVariation = leadIndex % 7 // Vary by up to 7 days based on lead index
  const hourVariation = (leadIndex * 3) % 24 // Vary hours

  const activities: LeadActivity[] = [
    {
      id: `${leadId}-act-1`,
      type: 'note',
      description: 'Lead added to system',
      timestamp: generateVariedDate(now, 25 + dayVariation, hourVariation),
      performedBy: 'Sarah Chen',
    },
  ]

  if (stage !== 'prospecting') {
    activities.push({
      id: `${leadId}-act-2`,
      type: 'email',
      description: 'Initial outreach email sent',
      timestamp: generateVariedDate(now, 18 + dayVariation, hourVariation + 4),
      performedBy: 'Sarah Chen',
    })
  }

  if (['meeting_scheduled', 'proposal_sent', 'negotiating', 'onboarding', 'converted'].includes(stage)) {
    activities.push({
      id: `${leadId}-act-3`,
      type: 'call',
      description: 'Discovery call completed',
      timestamp: generateVariedDate(now, 12 + dayVariation, hourVariation - 2),
      performedBy: 'Sarah Chen',
    })
  }

  if (['proposal_sent', 'negotiating', 'onboarding', 'converted'].includes(stage)) {
    activities.push({
      id: `${leadId}-act-4`,
      type: 'meeting',
      description: 'Product demo presentation',
      timestamp: generateVariedDate(now, 8 + dayVariation, hourVariation + 2),
      performedBy: 'Sarah Chen',
    })
  }

  if (['negotiating', 'onboarding', 'converted'].includes(stage)) {
    activities.push({
      id: `${leadId}-act-5`,
      type: 'note',
      description: 'Proposal sent to decision makers',
      timestamp: generateVariedDate(now, 3 + dayVariation, hourVariation + 1),
      performedBy: 'Sarah Chen',
    })
  }

  return activities
}

export const mockLeads: Lead[] = [
  {
    id: 'lead-001',
    companyName: 'Reddit, Inc.',
    industry: 'Technology',
    country: 'United States',
    contactEmail: 'ir@reddit.com',
    contactPhone: '+1-415-508-3500',
    contactName: 'Steve Huffman',
    status: 'active',
    pipelineStage: 'negotiating',
    aiScore: 88,
    aiScoreBreakdown: {
      companySize: 85,
      industry: 90,
      geography: 85,
      contactQuality: 92,
      overall: 88,
    },
    createdAt: '2023-09-15T10:00:00Z',
    updatedAt: '2024-03-20T16:45:00Z',
    assignedTo: 'rm-001',
    assignedToName: 'Sarah Chen',
    notes: 'Reddit IPO completed March 2024. Goldman Sachs served as lead left bookrunner. IPO raised $748M at $6.4B valuation (NYSE: RDDT). Company valued at $10-15 billion post-IPO. Strong growth in advertising revenue. Ongoing banking relationship for treasury services.',
    activities: generateActivities('lead-001', 'negotiating', 0, new Date('2024-03-21T12:00:00Z')),
    estimatedRevenue: 25000000, // $25M estimated investment banking fees
    expectedCloseDate: '2024-03-21',
    companySize: '2000+ employees',
    website: 'https://www.redditinc.com',
    linkedin: 'https://www.linkedin.com/company/reddit',
  },
  {
    id: 'lead-002',
    companyName: 'Stability AI Ltd.',
    industry: 'Technology',
    country: 'United Kingdom',
    contactEmail: 'enterprise@stability.ai',
    contactPhone: '+44-20-7946-0958',
    contactName: 'Emad Mostaque',
    status: 'active',
    pipelineStage: 'proposal_sent',
    aiScore: 82,
    aiScoreBreakdown: {
      companySize: 75,
      industry: 95,
      geography: 80,
      contactQuality: 78,
      overall: 82,
    },
    createdAt: '2024-12-10T09:00:00Z',
    updatedAt: '2025-01-12T14:30:00Z',
    assignedTo: 'rm-001',
    assignedToName: 'Sarah Chen',
    notes: 'AI image generation company exploring Series B funding round. Proposal submitted for investment banking services. Company developing Stable Diffusion models. Seeking $100-150M in funding.',
    activities: generateActivities('lead-002', 'proposal_sent', 1),
    estimatedRevenue: 8000000, // $8M estimated fees
    expectedCloseDate: '2025-02-28',
    companySize: '200-500 employees',
    website: 'https://stability.ai',
    linkedin: 'https://www.linkedin.com/company/stability-ai',
  },
  {
    id: 'lead-003',
    companyName: 'Discord, Inc.',
    industry: 'Technology',
    country: 'United States',
    contactEmail: 'business@discord.com',
    contactPhone: '+1-415-963-9639',
    contactName: 'Jason Citron',
    status: 'active',
    pipelineStage: 'meeting_scheduled',
    aiScore: 90,
    aiScoreBreakdown: {
      companySize: 88,
      industry: 95,
      geography: 90,
      contactQuality: 87,
      overall: 90,
    },
    createdAt: '2025-01-08T11:30:00Z',
    updatedAt: '2025-01-13T10:15:00Z',
    assignedTo: 'rm-002',
    assignedToName: 'Michael Torres',
    notes: 'Discord exploring strategic options including potential IPO or sale. Meeting scheduled with CEO and CFO. Company valued at $15-20 billion. Strong user growth and engagement metrics.',
    activities: generateActivities('lead-003', 'meeting_scheduled', 2),
    estimatedRevenue: 35000000, // $35M estimated fees for IPO
    expectedCloseDate: '2025-06-01',
    companySize: '600+ employees',
    website: 'https://discord.com',
    linkedin: 'https://www.linkedin.com/company/discord',
  },
  {
    id: 'lead-004',
    companyName: 'SpaceX',
    industry: 'Technology',
    country: 'United States',
    contactEmail: 'business@spacex.com',
    contactPhone: '+1-310-363-6000',
    contactName: 'Elon Musk',
    status: 'active',
    pipelineStage: 'contact_made',
    aiScore: 95,
    aiScoreBreakdown: {
      companySize: 95,
      industry: 100,
      geography: 90,
      contactQuality: 95,
      overall: 95,
    },
    createdAt: '2025-01-10T14:20:00Z',
    updatedAt: '2025-01-11T09:30:00Z',
    assignedTo: 'rm-002',
    assignedToName: 'Michael Torres',
    notes: 'Initial contact made with SpaceX CFO regarding potential financing options. Company exploring various capital raising strategies. Valued at $180+ billion. High-profile opportunity.',
    activities: generateActivities('lead-004', 'contact_made', 3),
    estimatedRevenue: 50000000, // $50M+ estimated fees for large financing
    expectedCloseDate: '2025-09-01',
    companySize: '13000+ employees',
    website: 'https://www.spacex.com',
    linkedin: 'https://www.linkedin.com/company/spacex',
  },
  {
    id: 'lead-005',
    companyName: 'Epic Games, Inc.',
    industry: 'Technology',
    country: 'United States',
    contactEmail: 'business@epicgames.com',
    contactPhone: '+1-919-854-0070',
    contactName: 'Tim Sweeney',
    status: 'active',
    pipelineStage: 'prospecting',
    aiScore: 85,
    aiScoreBreakdown: {
      companySize: 90,
      industry: 85,
      geography: 85,
      contactQuality: 80,
      overall: 85,
    },
    createdAt: '2025-01-12T08:45:00Z',
    updatedAt: '2025-01-12T08:45:00Z',
    assignedTo: 'rm-003',
    assignedToName: 'Lisa Wang',
    notes: 'New lead from industry research. Epic Games (Fortnite, Unreal Engine) exploring strategic options. Company valued at $32+ billion. Need to research and qualify opportunity.',
    activities: generateActivities('lead-005', 'prospecting', 4),
    estimatedRevenue: 40000000, // $40M estimated fees
    companySize: '1000+ employees',
    website: 'https://www.epicgames.com',
    linkedin: 'https://www.linkedin.com/company/epic-games',
  },
  {
    id: 'lead-006',
    companyName: 'Figma, Inc.',
    industry: 'Technology',
    country: 'United States',
    contactEmail: 'enterprise@figma.com',
    contactPhone: '+1-415-915-4000',
    contactName: 'Dylan Field',
    status: 'active',
    pipelineStage: 'onboarding',
    aiScore: 92,
    aiScoreBreakdown: {
      companySize: 88,
      industry: 95,
      geography: 90,
      contactQuality: 95,
      overall: 92,
    },
    createdAt: '2024-12-15T10:00:00Z',
    updatedAt: '2025-01-10T11:20:00Z',
    assignedTo: 'rm-001',
    assignedToName: 'Sarah Chen',
    notes: 'Figma selected Goldman Sachs for investment banking services. Contract signed! Beginning onboarding process. Design software company valued at $10+ billion. Adobe acquisition attempt blocked by regulators in 2023.',
    activities: generateActivities('lead-006', 'onboarding', 5, new Date('2025-01-10T12:00:00Z')),
    estimatedRevenue: 20000000, // $20M estimated fees
    expectedCloseDate: '2025-01-18',
    companySize: '500+ employees',
    website: 'https://www.figma.com',
    linkedin: 'https://www.linkedin.com/company/figma',
  },
  {
    id: 'lead-007',
    companyName: 'Notion Labs Inc.',
    industry: 'Technology',
    country: 'United States',
    contactEmail: 'business@notion.so',
    contactPhone: '+1-415-200-0562',
    contactName: 'Ivan Zhao',
    status: 'active',
    pipelineStage: 'proposal_sent',
    aiScore: 87,
    aiScoreBreakdown: {
      companySize: 85,
      industry: 90,
      geography: 85,
      contactQuality: 88,
      overall: 87,
    },
    createdAt: '2025-01-03T13:15:00Z',
    updatedAt: '2025-01-11T15:40:00Z',
    assignedTo: 'rm-003',
    assignedToName: 'Lisa Wang',
    notes: 'Notion exploring Series C funding or strategic options. Proposal under review. Productivity software company with strong enterprise adoption. Valued at $10+ billion.',
    activities: generateActivities('lead-007', 'proposal_sent', 6),
    estimatedRevenue: 12000000, // $12M estimated fees
    expectedCloseDate: '2025-03-15',
    companySize: '400+ employees',
    website: 'https://www.notion.so',
    linkedin: 'https://www.linkedin.com/company/notion',
  },
  {
    id: 'lead-008',
    companyName: 'Canva Pty Ltd.',
    industry: 'Technology',
    country: 'Australia',
    contactEmail: 'enterprise@canva.com',
    contactPhone: '+61-2-8274-8000',
    contactName: 'Melanie Perkins',
    status: 'active',
    pipelineStage: 'contact_made',
    aiScore: 89,
    aiScoreBreakdown: {
      companySize: 90,
      industry: 90,
      geography: 85,
      contactQuality: 91,
      overall: 89,
    },
    createdAt: '2025-01-09T10:30:00Z',
    updatedAt: '2025-01-10T14:20:00Z',
    assignedTo: 'rm-002',
    assignedToName: 'Michael Torres',
    notes: 'Canva exploring IPO options. Initial contact made with CFO. Design platform company valued at $40+ billion. Strong growth in enterprise segment. Following up next week.',
    activities: generateActivities('lead-008', 'contact_made', 7),
    estimatedRevenue: 45000000, // $45M estimated fees for IPO
    expectedCloseDate: '2025-12-01',
    companySize: '4000+ employees',
    website: 'https://www.canva.com',
    linkedin: 'https://www.linkedin.com/company/canva',
  },
  {
    id: 'lead-009',
    companyName: 'Klaviyo, Inc.',
    industry: 'Technology',
    country: 'United States',
    contactEmail: 'business@klaviyo.com',
    contactPhone: '+1-857-400-6900',
    contactName: 'Andrew Bialecki',
    status: 'active',
    pipelineStage: 'meeting_scheduled',
    aiScore: 83,
    aiScoreBreakdown: {
      companySize: 80,
      industry: 88,
      geography: 85,
      contactQuality: 79,
      overall: 83,
    },
    createdAt: '2025-01-07T09:45:00Z',
    updatedAt: '2025-01-12T11:10:00Z',
    assignedTo: 'rm-001',
    assignedToName: 'Sarah Chen',
    notes: 'Klaviyo already went public (NYSE: KVYO) in 2023. Exploring follow-on offerings or strategic transactions. Product demo scheduled. Email marketing platform with strong e-commerce focus.',
    activities: generateActivities('lead-009', 'meeting_scheduled', 8),
    estimatedRevenue: 15000000, // $15M estimated fees
    expectedCloseDate: '2025-04-01',
    companySize: '1000+ employees',
    website: 'https://www.klaviyo.com',
    linkedin: 'https://www.linkedin.com/company/klaviyo',
  },
  {
    id: 'lead-010',
    companyName: 'Scale AI, Inc.',
    industry: 'Technology',
    country: 'United States',
    contactEmail: 'enterprise@scale.ai',
    contactPhone: '+1-415-941-0332',
    contactName: 'Alexandr Wang',
    status: 'active',
    pipelineStage: 'negotiating',
    aiScore: 91,
    aiScoreBreakdown: {
      companySize: 88,
      industry: 95,
      geography: 90,
      contactQuality: 91,
      overall: 91,
    },
    createdAt: '2024-12-15T11:00:00Z',
    updatedAt: '2025-01-13T16:30:00Z',
    assignedTo: 'rm-003',
    assignedToName: 'Lisa Wang',
    notes: 'Scale AI exploring Series F funding round. Final contract review. AI data annotation and training data company. Valued at $14+ billion. Strong government contracts and enterprise clients.',
    activities: generateActivities('lead-010', 'negotiating', 9),
    estimatedRevenue: 18000000, // $18M estimated fees
    expectedCloseDate: '2025-01-20',
    companySize: '600+ employees',
    website: 'https://scale.ai',
    linkedin: 'https://www.linkedin.com/company/scale-ai',
  },
  {
    id: 'lead-011',
    companyName: 'Character.AI',
    industry: 'Technology',
    country: 'United States',
    contactEmail: 'business@character.ai',
    contactPhone: '+1-650-200-0000',
    contactName: 'Noam Shazeer',
    status: 'active',
    pipelineStage: 'prospecting',
    aiScore: 78,
    aiScoreBreakdown: {
      companySize: 70,
      industry: 90,
      geography: 80,
      contactQuality: 72,
      overall: 78,
    },
    createdAt: '2025-01-11T14:30:00Z',
    updatedAt: '2025-01-11T14:30:00Z',
    assignedTo: 'rm-002',
    assignedToName: 'Michael Torres',
    notes: 'Inbound inquiry from Character.AI. Conversational AI platform company. Need to qualify and understand requirements. Company raised $150M Series A in 2023 at $1B valuation.',
    activities: generateActivities('lead-011', 'prospecting', 10),
    estimatedRevenue: 6000000, // $6M estimated fees
    companySize: '100+ employees',
    website: 'https://www.character.ai',
    linkedin: 'https://www.linkedin.com/company/character-ai',
  },
  {
    id: 'lead-012',
    companyName: 'Plaid Inc.',
    industry: 'Financial Services',
    country: 'United States',
    contactEmail: 'enterprise@plaid.com',
    contactPhone: '+1-415-967-7900',
    contactName: 'Zach Perret',
    status: 'active',
    pipelineStage: 'proposal_sent',
    aiScore: 93,
    aiScoreBreakdown: {
      companySize: 90,
      industry: 95,
      geography: 90,
      contactQuality: 97,
      overall: 93,
    },
    createdAt: '2025-01-04T10:15:00Z',
    updatedAt: '2025-01-11T12:45:00Z',
    assignedTo: 'rm-001',
    assignedToName: 'Sarah Chen',
    notes: 'Plaid exploring strategic options including potential IPO. Proposal submitted. Financial data connectivity platform. Valued at $13+ billion. Visa acquisition attempt blocked in 2021.',
    activities: generateActivities('lead-012', 'proposal_sent', 11),
    estimatedRevenue: 30000000, // $30M estimated fees for IPO
    expectedCloseDate: '2025-05-01',
    companySize: '1200+ employees',
    website: 'https://plaid.com',
    linkedin: 'https://www.linkedin.com/company/plaid',
  },
  {
    id: 'lead-013',
    companyName: 'Chime Financial, Inc.',
    industry: 'Financial Services',
    country: 'United States',
    contactEmail: 'business@chime.com',
    contactPhone: '+1-415-549-2500',
    contactName: 'Chris Britt',
    status: 'active',
    pipelineStage: 'contact_made',
    aiScore: 88,
    aiScoreBreakdown: {
      companySize: 90,
      industry: 95,
      geography: 85,
      contactQuality: 82,
      overall: 88,
    },
    createdAt: '2025-01-10T11:20:00Z',
    updatedAt: '2025-01-11T09:15:00Z',
    assignedTo: 'rm-003',
    assignedToName: 'Lisa Wang',
    notes: 'Initial discovery call completed with Chime. Digital banking platform exploring IPO. Company valued at $25+ billion. Will send follow-up materials and proposal.',
    activities: generateActivities('lead-013', 'contact_made', 12),
    estimatedRevenue: 40000000, // $40M estimated fees for IPO
    expectedCloseDate: '2025-08-01',
    companySize: '1400+ employees',
    website: 'https://www.chime.com',
    linkedin: 'https://www.linkedin.com/company/chime',
  },
  {
    id: 'lead-014',
    companyName: 'Anduril Industries',
    industry: 'Technology',
    country: 'United States',
    contactEmail: 'business@anduril.com',
    contactPhone: '+1-949-478-7000',
    contactName: 'Brian Schimpf',
    status: 'active',
    pipelineStage: 'meeting_scheduled',
    aiScore: 86,
    aiScoreBreakdown: {
      companySize: 85,
      industry: 88,
      geography: 85,
      contactQuality: 86,
      overall: 86,
    },
    createdAt: '2025-01-06T13:40:00Z',
    updatedAt: '2025-01-12T10:25:00Z',
    assignedTo: 'rm-002',
    assignedToName: 'Michael Torres',
    notes: 'Demo scheduled for Thursday. Anduril (defense technology) exploring financing options. Company valued at $8+ billion. Strong government contracts. Focus on autonomous defense systems.',
    activities: generateActivities('lead-014', 'meeting_scheduled', 13),
    estimatedRevenue: 15000000, // $15M estimated fees
    expectedCloseDate: '2025-04-15',
    companySize: '1800+ employees',
    website: 'https://www.anduril.com',
    linkedin: 'https://www.linkedin.com/company/anduril',
  },
  {
    id: 'lead-015',
    companyName: 'Klarna Bank AB',
    industry: 'Financial Services',
    country: 'Sweden',
    contactEmail: 'enterprise@klarna.com',
    contactPhone: '+46-8-120-120-00',
    contactName: 'Sebastian Siemiatkowski',
    status: 'active',
    pipelineStage: 'prospecting',
    aiScore: 84,
    aiScoreBreakdown: {
      companySize: 85,
      industry: 90,
      geography: 80,
      contactQuality: 81,
      overall: 84,
    },
    createdAt: '2025-01-13T09:00:00Z',
    updatedAt: '2025-01-13T09:00:00Z',
    assignedTo: 'rm-001',
    assignedToName: 'Sarah Chen',
    notes: 'Referral from existing client. Klarna (buy now, pay later) exploring US expansion financing. Need to make initial contact. Company valued at $6+ billion. Publicly traded in Sweden.',
    activities: generateActivities('lead-015', 'prospecting', 14),
    estimatedRevenue: 12000000, // $12M estimated fees
    companySize: '5000+ employees',
    website: 'https://www.klarna.com',
    linkedin: 'https://www.linkedin.com/company/klarna',
  },
  {
    id: 'lead-016',
    companyName: 'Ripple Labs Inc.',
    industry: 'Financial Services',
    country: 'United States',
    contactEmail: 'business@ripple.com',
    contactPhone: '+1-415-967-7000',
    contactName: 'Brad Garlinghouse',
    status: 'active',
    pipelineStage: 'negotiating',
    aiScore: 79,
    aiScoreBreakdown: {
      companySize: 80,
      industry: 85,
      geography: 75,
      contactQuality: 76,
      overall: 79,
    },
    createdAt: '2024-12-20T10:30:00Z',
    updatedAt: '2025-01-08T14:15:00Z',
    assignedTo: 'rm-003',
    assignedToName: 'Lisa Wang',
    notes: 'Contract negotiations in final stages. Ripple (blockchain payments) exploring strategic options. SEC lawsuit recently resolved. Procurement review this week.',
    activities: generateActivities('lead-016', 'negotiating', 15, new Date('2025-01-08T12:00:00Z')),
    estimatedRevenue: 20000000, // $20M estimated fees
    expectedCloseDate: '2025-02-15',
    companySize: '900+ employees',
    website: 'https://ripple.com',
    linkedin: 'https://www.linkedin.com/company/ripple-labs',
  },
  {
    id: 'lead-017',
    companyName: 'CoreWeave, Inc.',
    industry: 'Technology',
    country: 'United States',
    contactEmail: 'enterprise@coreweave.com',
    contactPhone: '+1-201-984-1444',
    contactName: 'Michael Intrator',
    status: 'active',
    pipelineStage: 'contact_made',
    aiScore: 81,
    aiScoreBreakdown: {
      companySize: 78,
      industry: 90,
      geography: 80,
      contactQuality: 76,
      overall: 81,
    },
    createdAt: '2025-01-09T15:20:00Z',
    updatedAt: '2025-01-10T11:30:00Z',
    assignedTo: 'rm-002',
    assignedToName: 'Michael Torres',
    notes: 'Follow-up call scheduled for next week. CoreWeave (GPU cloud infrastructure) exploring Series C funding. Interested in AI infrastructure financing. Company valued at $19+ billion.',
    activities: generateActivities('lead-017', 'contact_made', 16),
    estimatedRevenue: 18000000, // $18M estimated fees
    expectedCloseDate: '2025-05-01',
    companySize: '400+ employees',
    website: 'https://www.coreweave.com',
    linkedin: 'https://www.linkedin.com/company/coreweave',
  },
  {
    id: 'lead-018',
    companyName: 'Hugging Face, Inc.',
    industry: 'Technology',
    country: 'United States',
    contactEmail: 'business@huggingface.co',
    contactPhone: '+1-415-200-0000',
    contactName: 'Clement Delangue',
    status: 'active',
    pipelineStage: 'proposal_sent',
    aiScore: 85,
    aiScoreBreakdown: {
      companySize: 82,
      industry: 95,
      geography: 80,
      contactQuality: 83,
      overall: 85,
    },
    createdAt: '2025-01-02T12:00:00Z',
    updatedAt: '2025-01-11T16:20:00Z',
    assignedTo: 'rm-001',
    assignedToName: 'Sarah Chen',
    notes: 'Comprehensive proposal submitted. Hugging Face (AI model hosting) exploring Series D funding. Strong fit for our AI/ML expertise. Company valued at $4+ billion.',
    activities: generateActivities('lead-018', 'proposal_sent', 17),
    estimatedRevenue: 10000000, // $10M estimated fees
    expectedCloseDate: '2025-03-01',
    companySize: '300+ employees',
    website: 'https://huggingface.co',
    linkedin: 'https://www.linkedin.com/company/hugging-face',
  },
  {
    id: 'lead-019',
    companyName: 'Flexport, Inc.',
    industry: 'Manufacturing',
    country: 'United States',
    contactEmail: 'enterprise@flexport.com',
    contactPhone: '+1-415-229-2800',
    contactName: 'Ryan Petersen',
    status: 'active',
    pipelineStage: 'meeting_scheduled',
    aiScore: 80,
    aiScoreBreakdown: {
      companySize: 82,
      industry: 75,
      geography: 85,
      contactQuality: 78,
      overall: 80,
    },
    createdAt: '2025-01-08T08:30:00Z',
    updatedAt: '2025-01-12T13:45:00Z',
    assignedTo: 'rm-003',
    assignedToName: 'Lisa Wang',
    notes: 'Demo next Monday. Flexport (logistics technology) exploring strategic options. Focus on supply chain financing and working capital solutions. Company valued at $8+ billion.',
    activities: generateActivities('lead-019', 'meeting_scheduled', 18),
    estimatedRevenue: 15000000, // $15M estimated fees
    expectedCloseDate: '2025-04-01',
    companySize: '3000+ employees',
    website: 'https://www.flexport.com',
    linkedin: 'https://www.linkedin.com/company/flexport',
  },
  {
    id: 'lead-020',
    companyName: 'Brex, Inc.',
    industry: 'Financial Services',
    country: 'United States',
    contactEmail: 'enterprise@brex.com',
    contactPhone: '+1-415-967-7900',
    contactName: 'Henrique Dubugras',
    status: 'active',
    pipelineStage: 'onboarding',
    aiScore: 87,
    aiScoreBreakdown: {
      companySize: 85,
      industry: 92,
      geography: 85,
      contactQuality: 86,
      overall: 87,
    },
    createdAt: '2024-11-25T10:00:00Z',
    updatedAt: '2025-01-05T10:50:00Z',
    assignedTo: 'rm-002',
    assignedToName: 'Michael Torres',
    notes: 'Contract signed! Onboarding in progress. High-profile client. Brex selected Goldman Sachs for investment banking services. Corporate card and expense management platform valued at $12+ billion.',
    activities: generateActivities('lead-020', 'onboarding', 19, new Date('2025-01-05T12:00:00Z')),
    estimatedRevenue: 20000000, // $20M estimated fees
    expectedCloseDate: '2025-01-22',
    companySize: '1200+ employees',
    website: 'https://www.brex.com',
    linkedin: 'https://www.linkedin.com/company/brexhq',
  },
]
