import { Lead, Industry, PipelineStage, LeadActivity } from '@/lib/types/lead'

// Helper to generate mock activities
function generateActivities(leadId: string, stage: PipelineStage): LeadActivity[] {
  const activities: LeadActivity[] = [
    {
      id: `${leadId}-act-1`,
      type: 'note',
      description: 'Lead added to system',
      timestamp: '2025-01-05T10:00:00Z',
      performedBy: 'Sarah Chen',
    },
  ]

  if (stage !== 'prospecting') {
    activities.push({
      id: `${leadId}-act-2`,
      type: 'email',
      description: 'Initial outreach email sent',
      timestamp: '2025-01-06T14:30:00Z',
      performedBy: 'Sarah Chen',
    })
  }

  if (['meeting_scheduled', 'proposal_sent', 'negotiating', 'onboarding', 'converted'].includes(stage)) {
    activities.push({
      id: `${leadId}-act-3`,
      type: 'call',
      description: 'Discovery call completed',
      timestamp: '2025-01-08T11:00:00Z',
      performedBy: 'Sarah Chen',
    })
  }

  if (['proposal_sent', 'negotiating', 'onboarding', 'converted'].includes(stage)) {
    activities.push({
      id: `${leadId}-act-4`,
      type: 'meeting',
      description: 'Product demo presentation',
      timestamp: '2025-01-10T15:00:00Z',
      performedBy: 'Sarah Chen',
    })
  }

  if (['negotiating', 'onboarding', 'converted'].includes(stage)) {
    activities.push({
      id: `${leadId}-act-5`,
      type: 'note',
      description: 'Proposal sent to decision makers',
      timestamp: '2025-01-12T09:00:00Z',
      performedBy: 'Sarah Chen',
    })
  }

  return activities
}

export const mockLeads: Lead[] = [
  {
    id: 'lead-001',
    companyName: 'Apex Financial Group',
    industry: 'Financial Services',
    country: 'United States',
    contactEmail: 'john.mitchell@apexfin.com',
    contactPhone: '+1-212-555-0123',
    contactName: 'John Mitchell',
    status: 'active',
    pipelineStage: 'proposal_sent',
    aiScore: 85,
    aiScoreBreakdown: {
      companySize: 90,
      industry: 95,
      geography: 80,
      contactQuality: 75,
      overall: 85,
    },
    createdAt: '2025-01-05T10:00:00Z',
    updatedAt: '2025-01-12T14:30:00Z',
    assignedTo: 'rm-001',
    assignedToName: 'Sarah Chen',
    notes: 'High-value prospect. CFO is very interested in our compliance automation platform.',
    activities: generateActivities('lead-001', 'proposal_sent'),
    estimatedRevenue: 250000,
    expectedCloseDate: '2025-02-15',
    companySize: '500-1000 employees',
    website: 'https://apexfin.com',
  },
  {
    id: 'lead-002',
    companyName: 'TechVentures Capital',
    industry: 'Financial Services',
    country: 'United Kingdom',
    contactEmail: 'emma.watson@techventures.co.uk',
    contactPhone: '+44-20-7946-0958',
    contactName: 'Emma Watson',
    status: 'active',
    pipelineStage: 'negotiating',
    aiScore: 92,
    aiScoreBreakdown: {
      companySize: 95,
      industry: 100,
      geography: 85,
      contactQuality: 88,
      overall: 92,
    },
    createdAt: '2024-12-10T09:00:00Z',
    updatedAt: '2025-01-14T16:45:00Z',
    assignedTo: 'rm-001',
    assignedToName: 'Sarah Chen',
    notes: 'Final negotiations ongoing. Expecting signature next week.',
    activities: generateActivities('lead-002', 'negotiating'),
    estimatedRevenue: 500000,
    expectedCloseDate: '2025-01-25',
    companySize: '1000+ employees',
    website: 'https://techventures.co.uk',
  },
  {
    id: 'lead-003',
    companyName: 'GlobalTrade Solutions',
    industry: 'Manufacturing',
    country: 'Germany',
    contactEmail: 'klaus.schmidt@globaltrade.de',
    contactPhone: '+49-30-123-4567',
    contactName: 'Klaus Schmidt',
    status: 'active',
    pipelineStage: 'meeting_scheduled',
    aiScore: 78,
    aiScoreBreakdown: {
      companySize: 80,
      industry: 70,
      geography: 85,
      contactQuality: 77,
      overall: 78,
    },
    createdAt: '2025-01-08T11:30:00Z',
    updatedAt: '2025-01-13T10:15:00Z',
    assignedTo: 'rm-002',
    assignedToName: 'Michael Torres',
    notes: 'Demo scheduled for next Tuesday. Focus on manufacturing compliance features.',
    activities: generateActivities('lead-003', 'meeting_scheduled'),
    estimatedRevenue: 180000,
    expectedCloseDate: '2025-03-01',
    companySize: '250-500 employees',
    website: 'https://globaltrade.de',
  },
  {
    id: 'lead-004',
    companyName: 'MediCare Plus',
    industry: 'Healthcare',
    country: 'Canada',
    contactEmail: 'dr.sarah.johnson@medicareplus.ca',
    contactPhone: '+1-416-555-0199',
    contactName: 'Dr. Sarah Johnson',
    status: 'active',
    pipelineStage: 'contact_made',
    aiScore: 71,
    aiScoreBreakdown: {
      companySize: 65,
      industry: 80,
      geography: 70,
      contactQuality: 69,
      overall: 71,
    },
    createdAt: '2025-01-10T14:20:00Z',
    updatedAt: '2025-01-11T09:30:00Z',
    assignedTo: 'rm-002',
    assignedToName: 'Michael Torres',
    notes: 'Initial contact made. Waiting for callback from compliance director.',
    activities: generateActivities('lead-004', 'contact_made'),
    estimatedRevenue: 120000,
    expectedCloseDate: '2025-04-01',
    companySize: '100-250 employees',
    website: 'https://medicareplus.ca',
  },
  {
    id: 'lead-005',
    companyName: 'RetailHub International',
    industry: 'Retail',
    country: 'Australia',
    contactEmail: 'james.brown@retailhub.au',
    contactPhone: '+61-2-9876-5432',
    contactName: 'James Brown',
    status: 'active',
    pipelineStage: 'prospecting',
    aiScore: 65,
    aiScoreBreakdown: {
      companySize: 70,
      industry: 60,
      geography: 65,
      contactQuality: 65,
      overall: 65,
    },
    createdAt: '2025-01-12T08:45:00Z',
    updatedAt: '2025-01-12T08:45:00Z',
    assignedTo: 'rm-003',
    assignedToName: 'Lisa Wang',
    notes: 'New lead from marketing campaign. Need to research and qualify.',
    activities: generateActivities('lead-005', 'prospecting'),
    estimatedRevenue: 95000,
    companySize: '50-100 employees',
    website: 'https://retailhub.au',
  },
  {
    id: 'lead-006',
    companyName: 'EnergyTech Corp',
    industry: 'Energy',
    country: 'United States',
    contactEmail: 'robert.davis@energytech.com',
    contactPhone: '+1-713-555-0145',
    contactName: 'Robert Davis',
    status: 'active',
    pipelineStage: 'onboarding',
    aiScore: 88,
    aiScoreBreakdown: {
      companySize: 85,
      industry: 90,
      geography: 90,
      contactQuality: 87,
      overall: 88,
    },
    createdAt: '2024-12-01T10:00:00Z',
    updatedAt: '2025-01-14T11:20:00Z',
    assignedTo: 'rm-001',
    assignedToName: 'Sarah Chen',
    notes: 'Contract signed! Beginning onboarding process.',
    activities: generateActivities('lead-006', 'onboarding'),
    estimatedRevenue: 350000,
    expectedCloseDate: '2025-01-18',
    companySize: '500-1000 employees',
    website: 'https://energytech.com',
  },
  // Additional leads
  {
    id: 'lead-007',
    companyName: 'CloudFirst Technologies',
    industry: 'Technology',
    country: 'Singapore',
    contactEmail: 'wei.zhang@cloudfirst.sg',
    contactPhone: '+65-6123-4567',
    contactName: 'Wei Zhang',
    status: 'active',
    pipelineStage: 'proposal_sent',
    aiScore: 82,
    aiScoreBreakdown: {
      companySize: 80,
      industry: 85,
      geography: 80,
      contactQuality: 83,
      overall: 82,
    },
    createdAt: '2025-01-03T13:15:00Z',
    updatedAt: '2025-01-11T15:40:00Z',
    assignedTo: 'rm-003',
    assignedToName: 'Lisa Wang',
    notes: 'Proposal under review. Strong interest in AI-powered risk assessment.',
    activities: generateActivities('lead-007', 'proposal_sent'),
    estimatedRevenue: 220000,
    expectedCloseDate: '2025-02-28',
    companySize: '250-500 employees',
    website: 'https://cloudfirst.sg',
  },
  {
    id: 'lead-008',
    companyName: 'PropTech Innovations',
    industry: 'Real Estate',
    country: 'United Arab Emirates',
    contactEmail: 'ahmed.ali@proptech.ae',
    contactPhone: '+971-4-123-4567',
    contactName: 'Ahmed Ali',
    status: 'active',
    pipelineStage: 'contact_made',
    aiScore: 74,
    aiScoreBreakdown: {
      companySize: 75,
      industry: 70,
      geography: 75,
      contactQuality: 76,
      overall: 74,
    },
    createdAt: '2025-01-09T10:30:00Z',
    updatedAt: '2025-01-10T14:20:00Z',
    assignedTo: 'rm-002',
    assignedToName: 'Michael Torres',
    notes: 'Interested in vendor compliance management. Following up next week.',
    activities: generateActivities('lead-008', 'contact_made'),
    estimatedRevenue: 165000,
    expectedCloseDate: '2025-03-15',
    companySize: '100-250 employees',
    website: 'https://proptech.ae',
  },
  {
    id: 'lead-009',
    companyName: 'TeleGlobal Communications',
    industry: 'Telecommunications',
    country: 'Brazil',
    contactEmail: 'maria.silva@teleglobal.br',
    contactPhone: '+55-11-3456-7890',
    contactName: 'Maria Silva',
    status: 'active',
    pipelineStage: 'meeting_scheduled',
    aiScore: 76,
    aiScoreBreakdown: {
      companySize: 78,
      industry: 72,
      geography: 75,
      contactQuality: 79,
      overall: 76,
    },
    createdAt: '2025-01-07T09:45:00Z',
    updatedAt: '2025-01-12T11:10:00Z',
    assignedTo: 'rm-001',
    assignedToName: 'Sarah Chen',
    notes: 'Product demo scheduled. They need LATAM-specific compliance features.',
    activities: generateActivities('lead-009', 'meeting_scheduled'),
    estimatedRevenue: 195000,
    expectedCloseDate: '2025-03-10',
    companySize: '500-1000 employees',
    website: 'https://teleglobal.br',
  },
  {
    id: 'lead-010',
    companyName: 'FinConsult Partners',
    industry: 'Consulting',
    country: 'Switzerland',
    contactEmail: 'thomas.mueller@finconsult.ch',
    contactPhone: '+41-44-123-4567',
    contactName: 'Thomas Mueller',
    status: 'active',
    pipelineStage: 'negotiating',
    aiScore: 90,
    aiScoreBreakdown: {
      companySize: 88,
      industry: 95,
      geography: 90,
      contactQuality: 87,
      overall: 90,
    },
    createdAt: '2024-12-15T11:00:00Z',
    updatedAt: '2025-01-13T16:30:00Z',
    assignedTo: 'rm-003',
    assignedToName: 'Lisa Wang',
    notes: 'Final contract review. Expect to close this week.',
    activities: generateActivities('lead-010', 'negotiating'),
    estimatedRevenue: 420000,
    expectedCloseDate: '2025-01-20',
    companySize: '100-250 employees',
    website: 'https://finconsult.ch',
  },
  {
    id: 'lead-011',
    companyName: 'Digital Banking Corp',
    industry: 'Financial Services',
    country: 'Japan',
    contactEmail: 'kenji.tanaka@digitalbk.jp',
    contactPhone: '+81-3-1234-5678',
    contactName: 'Kenji Tanaka',
    status: 'active',
    pipelineStage: 'prospecting',
    aiScore: 69,
    aiScoreBreakdown: {
      companySize: 72,
      industry: 75,
      geography: 65,
      contactQuality: 64,
      overall: 69,
    },
    createdAt: '2025-01-11T14:30:00Z',
    updatedAt: '2025-01-11T14:30:00Z',
    assignedTo: 'rm-002',
    assignedToName: 'Michael Torres',
    notes: 'Inbound inquiry. Need to qualify and understand requirements.',
    activities: generateActivities('lead-011', 'prospecting'),
    estimatedRevenue: 140000,
    companySize: '250-500 employees',
    website: 'https://digitalbk.jp',
  },
  {
    id: 'lead-012',
    companyName: 'GreenEnergy Solutions',
    industry: 'Energy',
    country: 'Netherlands',
    contactEmail: 'petra.van.der.meer@greenenergy.nl',
    contactPhone: '+31-20-123-4567',
    contactName: 'Petra van der Meer',
    status: 'active',
    pipelineStage: 'proposal_sent',
    aiScore: 81,
    aiScoreBreakdown: {
      companySize: 83,
      industry: 78,
      geography: 82,
      contactQuality: 81,
      overall: 81,
    },
    createdAt: '2025-01-04T10:15:00Z',
    updatedAt: '2025-01-11T12:45:00Z',
    assignedTo: 'rm-001',
    assignedToName: 'Sarah Chen',
    notes: 'Proposal submitted. Waiting for board approval.',
    activities: generateActivities('lead-012', 'proposal_sent'),
    estimatedRevenue: 275000,
    expectedCloseDate: '2025-02-20',
    companySize: '250-500 employees',
    website: 'https://greenenergy.nl',
  },
  {
    id: 'lead-013',
    companyName: 'MedTech Innovations',
    industry: 'Healthcare',
    country: 'South Korea',
    contactEmail: 'min.park@medtech-kr.com',
    contactPhone: '+82-2-1234-5678',
    contactName: 'Min Park',
    status: 'active',
    pipelineStage: 'contact_made',
    aiScore: 72,
    aiScoreBreakdown: {
      companySize: 70,
      industry: 76,
      geography: 70,
      contactQuality: 72,
      overall: 72,
    },
    createdAt: '2025-01-10T11:20:00Z',
    updatedAt: '2025-01-11T09:15:00Z',
    assignedTo: 'rm-003',
    assignedToName: 'Lisa Wang',
    notes: 'Initial discovery call completed. Will send follow-up materials.',
    activities: generateActivities('lead-013', 'contact_made'),
    estimatedRevenue: 155000,
    expectedCloseDate: '2025-04-15',
    companySize: '100-250 employees',
    website: 'https://medtech-kr.com',
  },
  {
    id: 'lead-014',
    companyName: 'AutoManufacture Group',
    industry: 'Manufacturing',
    country: 'India',
    contactEmail: 'rajesh.kumar@automanufacture.in',
    contactPhone: '+91-22-1234-5678',
    contactName: 'Rajesh Kumar',
    status: 'active',
    pipelineStage: 'meeting_scheduled',
    aiScore: 77,
    aiScoreBreakdown: {
      companySize: 80,
      industry: 73,
      geography: 75,
      contactQuality: 80,
      overall: 77,
    },
    createdAt: '2025-01-06T13:40:00Z',
    updatedAt: '2025-01-12T10:25:00Z',
    assignedTo: 'rm-002',
    assignedToName: 'Michael Torres',
    notes: 'Demo scheduled for Thursday. Focus on supply chain compliance.',
    activities: generateActivities('lead-014', 'meeting_scheduled'),
    estimatedRevenue: 190000,
    expectedCloseDate: '2025-03-05',
    companySize: '1000+ employees',
    website: 'https://automanufacture.in',
  },
  {
    id: 'lead-015',
    companyName: 'Fashion Retail Global',
    industry: 'Retail',
    country: 'France',
    contactEmail: 'sophie.dubois@fashionretail.fr',
    contactPhone: '+33-1-23-45-67-89',
    contactName: 'Sophie Dubois',
    status: 'active',
    pipelineStage: 'prospecting',
    aiScore: 63,
    aiScoreBreakdown: {
      companySize: 65,
      industry: 58,
      geography: 68,
      contactQuality: 61,
      overall: 63,
    },
    createdAt: '2025-01-13T09:00:00Z',
    updatedAt: '2025-01-13T09:00:00Z',
    assignedTo: 'rm-001',
    assignedToName: 'Sarah Chen',
    notes: 'Referral from existing client. Need to make initial contact.',
    activities: generateActivities('lead-015', 'prospecting'),
    estimatedRevenue: 88000,
    companySize: '50-100 employees',
    website: 'https://fashionretail.fr',
  },
  {
    id: 'lead-016',
    companyName: 'InsurancePlus Holdings',
    industry: 'Financial Services',
    country: 'United States',
    contactEmail: 'jennifer.wilson@insuranceplus.com',
    contactPhone: '+1-617-555-0167',
    contactName: 'Jennifer Wilson',
    status: 'active',
    pipelineStage: 'negotiating',
    aiScore: 87,
    aiScoreBreakdown: {
      companySize: 90,
      industry: 92,
      geography: 85,
      contactQuality: 81,
      overall: 87,
    },
    createdAt: '2024-12-20T10:30:00Z',
    updatedAt: '2025-01-14T14:15:00Z',
    assignedTo: 'rm-003',
    assignedToName: 'Lisa Wang',
    notes: 'Contract negotiations in final stages. Procurement review this week.',
    activities: generateActivities('lead-016', 'negotiating'),
    estimatedRevenue: 385000,
    expectedCloseDate: '2025-01-28',
    companySize: '500-1000 employees',
    website: 'https://insuranceplus.com',
  },
  {
    id: 'lead-017',
    companyName: 'DataSecure Systems',
    industry: 'Technology',
    country: 'Israel',
    contactEmail: 'david.cohen@datasecure.il',
    contactPhone: '+972-3-123-4567',
    contactName: 'David Cohen',
    status: 'active',
    pipelineStage: 'contact_made',
    aiScore: 70,
    aiScoreBreakdown: {
      companySize: 68,
      industry: 73,
      geography: 70,
      contactQuality: 69,
      overall: 70,
    },
    createdAt: '2025-01-09T15:20:00Z',
    updatedAt: '2025-01-10T11:30:00Z',
    assignedTo: 'rm-002',
    assignedToName: 'Michael Torres',
    notes: 'Follow-up call scheduled for next week. Interested in data compliance features.',
    activities: generateActivities('lead-017', 'contact_made'),
    estimatedRevenue: 145000,
    expectedCloseDate: '2025-04-01',
    companySize: '100-250 employees',
    website: 'https://datasecure.il',
  },
  {
    id: 'lead-018',
    companyName: 'Pharma Global Research',
    industry: 'Healthcare',
    country: 'Belgium',
    contactEmail: 'dr.anna.peters@pharmaglobal.be',
    contactPhone: '+32-2-123-4567',
    contactName: 'Dr. Anna Peters',
    status: 'active',
    pipelineStage: 'proposal_sent',
    aiScore: 84,
    aiScoreBreakdown: {
      companySize: 87,
      industry: 85,
      geography: 82,
      contactQuality: 82,
      overall: 84,
    },
    createdAt: '2025-01-02T12:00:00Z',
    updatedAt: '2025-01-11T16:20:00Z',
    assignedTo: 'rm-001',
    assignedToName: 'Sarah Chen',
    notes: 'Comprehensive proposal submitted. Strong fit for our pharma compliance module.',
    activities: generateActivities('lead-018', 'proposal_sent'),
    estimatedRevenue: 310000,
    expectedCloseDate: '2025-02-25',
    companySize: '250-500 employees',
    website: 'https://pharmaglobal.be',
  },
  {
    id: 'lead-019',
    companyName: 'ConstructTech Solutions',
    industry: 'Real Estate',
    country: 'United States',
    contactEmail: 'mike.anderson@constructtech.com',
    contactPhone: '+1-312-555-0198',
    contactName: 'Mike Anderson',
    status: 'active',
    pipelineStage: 'meeting_scheduled',
    aiScore: 75,
    aiScoreBreakdown: {
      companySize: 77,
      industry: 71,
      geography: 78,
      contactQuality: 74,
      overall: 75,
    },
    createdAt: '2025-01-08T08:30:00Z',
    updatedAt: '2025-01-12T13:45:00Z',
    assignedTo: 'rm-003',
    assignedToName: 'Lisa Wang',
    notes: 'Demo next Monday. Focus on contractor compliance and vendor management.',
    activities: generateActivities('lead-019', 'meeting_scheduled'),
    estimatedRevenue: 175000,
    expectedCloseDate: '2025-03-20',
    companySize: '250-500 employees',
    website: 'https://constructtech.com',
  },
  {
    id: 'lead-020',
    companyName: 'AeroSpace Dynamics',
    industry: 'Manufacturing',
    country: 'United Kingdom',
    contactEmail: 'richard.thompson@aerospace-dyn.co.uk',
    contactPhone: '+44-20-7946-0234',
    contactName: 'Richard Thompson',
    status: 'active',
    pipelineStage: 'onboarding',
    aiScore: 91,
    aiScoreBreakdown: {
      companySize: 93,
      industry: 90,
      geography: 90,
      contactQuality: 91,
      overall: 91,
    },
    createdAt: '2024-11-25T10:00:00Z',
    updatedAt: '2025-01-14T10:50:00Z',
    assignedTo: 'rm-002',
    assignedToName: 'Michael Torres',
    notes: 'Contract signed! Onboarding in progress. High-profile client.',
    activities: generateActivities('lead-020', 'onboarding'),
    estimatedRevenue: 575000,
    expectedCloseDate: '2025-01-22',
    companySize: '1000+ employees',
    website: 'https://aerospace-dyn.co.uk',
  },
  {
    id: 'lead-021',
    companyName: 'EduTech Platforms',
    industry: 'Technology',
    country: 'Sweden',
    contactEmail: 'lars.anderson@edutech.se',
    contactPhone: '+46-8-123-4567',
    contactName: 'Lars Andersson',
    status: 'active',
    pipelineStage: 'prospecting',
    aiScore: 67,
    aiScoreBreakdown: {
      companySize: 68,
      industry: 65,
      geography: 70,
      contactQuality: 65,
      overall: 67,
    },
    createdAt: '2025-01-14T11:15:00Z',
    updatedAt: '2025-01-14T11:15:00Z',
    assignedTo: 'rm-001',
    assignedToName: 'Sarah Chen',
    notes: 'New lead from conference. Need to research and schedule intro call.',
    activities: generateActivities('lead-021', 'prospecting'),
    estimatedRevenue: 105000,
    companySize: '50-100 employees',
    website: 'https://edutech.se',
  },
  {
    id: 'lead-022',
    companyName: 'Maritime Logistics Inc',
    industry: 'Manufacturing',
    country: 'Norway',
    contactEmail: 'kristin.olsen@maritime-log.no',
    contactPhone: '+47-22-123-456',
    contactName: 'Kristin Olsen',
    status: 'lost',
    pipelineStage: 'lost',
    aiScore: 73,
    aiScoreBreakdown: {
      companySize: 75,
      industry: 70,
      geography: 74,
      contactQuality: 73,
      overall: 73,
    },
    createdAt: '2024-11-15T09:30:00Z',
    updatedAt: '2025-01-10T14:00:00Z',
    assignedTo: 'rm-002',
    assignedToName: 'Michael Torres',
    notes: 'Lost to competitor. Price was the main factor. Follow up in 6 months.',
    activities: [
      ...generateActivities('lead-022', 'negotiating'),
      {
        id: 'lead-022-act-final',
        type: 'status_change',
        description: 'Lost to competitor - pricing',
        timestamp: '2025-01-10T14:00:00Z',
        performedBy: 'Michael Torres',
      },
    ],
    estimatedRevenue: 200000,
    companySize: '250-500 employees',
    website: 'https://maritime-log.no',
  },
]

