import { RiskScoreData, RiskLevel } from '@/components/compliance/risk-score-card'

// Generate realistic risk scores for clients and vendors
export const mockRiskScores: RiskScoreData[] = [
  {
    entityId: 'client-1',
    entityName: 'Global Innovations Inc.',
    entityType: 'client',
    overallScore: 45,
    riskLevel: 'Medium',
    breakdown: {
      geographic: 35,
      industry: 50,
      ownership: 40,
      compliance: 55,
      adverseMedia: 30,
      sanctions: 10,
    },
    lastAssessed: '2025-11-01T10:00:00Z',
    nextReview: '2026-02-01T10:00:00Z',
    flags: [
      'Operating in multiple high-risk jurisdictions',
      'Complex ownership structure requires additional due diligence',
    ],
    recommendations: [
      'Conduct enhanced due diligence on beneficial owners',
      'Implement quarterly compliance reviews',
      'Request additional documentation on offshore operations',
    ],
  },
  {
    entityId: 'client-2',
    entityName: 'FinTech Solutions Ltd.',
    entityType: 'client',
    overallScore: 22,
    riskLevel: 'Low',
    breakdown: {
      geographic: 15,
      industry: 30,
      ownership: 20,
      compliance: 25,
      adverseMedia: 10,
      sanctions: 5,
    },
    lastAssessed: '2025-10-15T14:00:00Z',
    nextReview: '2026-04-15T14:00:00Z',
    flags: [],
    recommendations: [
      'Maintain current monitoring frequency',
      'Continue annual compliance reviews',
    ],
  },
  {
    entityId: 'client-3',
    entityName: 'Alpha Holdings',
    entityType: 'client',
    overallScore: 68,
    riskLevel: 'High',
    breakdown: {
      geographic: 75,
      industry: 60,
      ownership: 70,
      compliance: 65,
      adverseMedia: 55,
      sanctions: 40,
    },
    lastAssessed: '2025-11-05T09:00:00Z',
    nextReview: '2025-12-05T09:00:00Z',
    flags: [
      'Recent adverse media mentions regarding regulatory investigation',
      'Operations in high-risk jurisdictions (3 countries)',
      'Complex multi-layered ownership structure',
      'Previous compliance violations in 2023',
    ],
    recommendations: [
      'Immediate enhanced due diligence required',
      'Monthly monitoring and reporting',
      'Senior management approval for all transactions',
      'Consider relationship exit strategy if risk escalates',
      'Engage external compliance consultant for review',
    ],
  },
  {
    entityId: 'vendor-1',
    entityName: 'TechSupply Corp',
    entityType: 'vendor',
    overallScore: 38,
    riskLevel: 'Medium',
    breakdown: {
      geographic: 45,
      industry: 35,
      ownership: 40,
      compliance: 35,
      adverseMedia: 20,
      sanctions: 15,
    },
    lastAssessed: '2025-10-20T11:00:00Z',
    nextReview: '2026-01-20T11:00:00Z',
    flags: [
      'Some operations in emerging markets with weak regulatory oversight',
    ],
    recommendations: [
      'Request annual financial statements',
      'Verify compliance certifications',
      'Conduct site visit within 6 months',
    ],
  },
  {
    entityId: 'vendor-2',
    entityName: 'SecureData Services',
    entityType: 'vendor',
    overallScore: 18,
    riskLevel: 'Low',
    breakdown: {
      geographic: 10,
      industry: 25,
      ownership: 15,
      compliance: 20,
      adverseMedia: 15,
      sanctions: 5,
    },
    lastAssessed: '2025-09-30T10:00:00Z',
    nextReview: '2026-09-30T10:00:00Z',
    flags: [],
    recommendations: [
      'Continue standard monitoring',
      'Annual review sufficient',
    ],
  },
  {
    entityId: 'vendor-3',
    entityName: 'GlobalShip Logistics',
    entityType: 'vendor',
    overallScore: 82,
    riskLevel: 'Critical',
    breakdown: {
      geographic: 85,
      industry: 80,
      ownership: 75,
      compliance: 90,
      adverseMedia: 70,
      sanctions: 60,
    },
    lastAssessed: '2025-11-08T15:00:00Z',
    nextReview: '2025-11-22T15:00:00Z',
    flags: [
      'CRITICAL: Sanctions screening match requires immediate review',
      'Significant adverse media regarding sanctions evasion allegations',
      'Operations in sanctioned territories',
      'Ownership links to PEPs (Politically Exposed Persons)',
      'Multiple regulatory violations across jurisdictions',
    ],
    recommendations: [
      'URGENT: Suspend all transactions pending investigation',
      'Escalate to senior management and legal team immediately',
      'Conduct full forensic investigation',
      'Report to regulatory authorities as required',
      'Prepare relationship termination documentation',
      'Notify clients of potential service disruption',
    ],
  },
  {
    entityId: 'client-4',
    entityName: 'MediCare Plus',
    entityType: 'client',
    overallScore: 28,
    riskLevel: 'Low',
    breakdown: {
      geographic: 25,
      industry: 35,
      ownership: 20,
      compliance: 30,
      adverseMedia: 25,
      sanctions: 10,
    },
    lastAssessed: '2025-10-10T12:00:00Z',
    nextReview: '2026-04-10T12:00:00Z',
    flags: ['Healthcare industry requires specialized compliance monitoring'],
    recommendations: [
      'Ensure HIPAA compliance documentation current',
      'Verify professional licenses and certifications',
      'Standard monitoring frequency appropriate',
    ],
  },
  {
    entityId: 'client-5',
    entityName: 'EnergyTech Corp',
    entityType: 'client',
    overallScore: 52,
    riskLevel: 'Medium',
    breakdown: {
      geographic: 60,
      industry: 55,
      ownership: 45,
      compliance: 50,
      adverseMedia: 40,
      sanctions: 30,
    },
    lastAssessed: '2025-11-03T13:00:00Z',
    nextReview: '2026-01-03T13:00:00Z',
    flags: [
      'Energy sector exposure to geopolitical risks',
      'Operations include high-risk jurisdictions',
    ],
    recommendations: [
      'Enhanced monitoring of jurisdictional risk',
      'Quarterly sanctions screening',
      'Review of environmental compliance record',
      'Assess exposure to sanctioned entities in supply chain',
    ],
  },
  {
    entityId: 'vendor-4',
    entityName: 'CloudInfra Solutions',
    entityType: 'vendor',
    overallScore: 25,
    riskLevel: 'Low',
    breakdown: {
      geographic: 20,
      industry: 30,
      ownership: 25,
      compliance: 20,
      adverseMedia: 15,
      sanctions: 5,
    },
    lastAssessed: '2025-09-15T09:00:00Z',
    nextReview: '2026-09-15T09:00:00Z',
    flags: [],
    recommendations: [
      'Verify SOC 2 Type II certification annually',
      'Review data security policies',
      'Standard annual review',
    ],
  },
  {
    entityId: 'client-6',
    entityName: 'Apex Financial Group',
    entityType: 'client',
    overallScore: 35,
    riskLevel: 'Medium',
    breakdown: {
      geographic: 40,
      industry: 45,
      ownership: 30,
      compliance: 35,
      adverseMedia: 25,
      sanctions: 15,
    },
    lastAssessed: '2025-10-25T11:00:00Z',
    nextReview: '2026-01-25T11:00:00Z',
    flags: [
      'Financial services sector requires enhanced AML monitoring',
    ],
    recommendations: [
      'Quarterly AML/CFT reviews',
      'Verify regulatory licenses current',
      'Monitor for changes in ownership structure',
    ],
  },
]

