import { RiskScoreData, RiskLevel } from '@/components/compliance/risk-score-card'

// Real company risk scores based on actual Goldman Sachs clients and vendors
export const mockRiskScores: RiskScoreData[] = [
  {
    entityId: 'client-001',
    entityName: 'OpenAI, Inc.',
    entityType: 'client',
    overallScore: 22,
    riskLevel: 'Low',
    breakdown: {
      geographic: 15,
      industry: 25,
      ownership: 20,
      compliance: 18,
      adverseMedia: 30,
      sanctions: 8,
    },
    lastAssessed: '2024-12-01T10:00:00Z',
    nextReview: '2025-06-01T10:00:00Z',
    flags: [
      'High-profile AI company with significant media attention',
      'Microsoft partnership and $13B investment requires ongoing monitoring',
    ],
    recommendations: [
      'Continue standard monitoring frequency',
      'Review Microsoft partnership structure annually',
      'Monitor for regulatory changes in AI industry',
      'Maintain enhanced due diligence on new investors',
    ],
  },
  {
    entityId: 'client-002',
    entityName: 'Stripe, Inc.',
    entityType: 'client',
    overallScore: 28,
    riskLevel: 'Low',
    breakdown: {
      geographic: 20,
      industry: 35,
      ownership: 25,
      compliance: 30,
      adverseMedia: 25,
      sanctions: 15,
    },
    lastAssessed: '2024-11-15T10:00:00Z',
    nextReview: '2025-05-15T10:00:00Z',
    flags: [
      'Fintech company requires enhanced AML/KYC monitoring',
      'High transaction volume requires ongoing compliance oversight',
    ],
    recommendations: [
      'Quarterly AML/CFT reviews',
      'Verify regulatory licenses remain current',
      'Monitor for changes in payment processing regulations',
      'Review transaction monitoring systems annually',
    ],
  },
  {
    entityId: 'client-003',
    entityName: 'Palantir Technologies Inc.',
    entityType: 'client',
    overallScore: 45,
    riskLevel: 'Medium',
    breakdown: {
      geographic: 50,
      industry: 40,
      ownership: 45,
      compliance: 48,
      adverseMedia: 50,
      sanctions: 35,
    },
    lastAssessed: '2024-10-01T10:00:00Z',
    nextReview: '2025-01-01T10:00:00Z',
    flags: [
      'Significant government contracts require enhanced due diligence',
      'Data privacy and security concerns due to government work',
      'Operating in multiple high-risk jurisdictions',
      'Complex ownership structure with government ties',
    ],
    recommendations: [
      'Conduct enhanced due diligence on government contracts',
      'Implement quarterly compliance reviews',
      'Request additional documentation on data security practices',
      'Monitor for changes in government contract relationships',
      'Review export control compliance annually',
    ],
  },
  {
    entityId: 'client-004',
    entityName: 'Coinbase Global, Inc.',
    entityType: 'client',
    overallScore: 52,
    riskLevel: 'Medium',
    breakdown: {
      geographic: 55,
      industry: 60,
      ownership: 45,
      compliance: 50,
      adverseMedia: 55,
      sanctions: 45,
    },
    lastAssessed: '2024-11-20T10:00:00Z',
    nextReview: '2025-02-20T10:00:00Z',
    flags: [
      'Cryptocurrency exchange requires enhanced AML monitoring',
      'Regulatory scrutiny in crypto industry',
      'High-risk industry with evolving regulations',
      'Sanctions screening critical due to crypto transactions',
    ],
    recommendations: [
      'Enhanced monitoring of AML/CFT compliance',
      'Quarterly sanctions screening',
      'Review of regulatory compliance record',
      'Monitor for changes in crypto regulations',
      'Assess exposure to sanctioned entities in crypto ecosystem',
      'Monthly compliance reporting',
    ],
  },
  {
    entityId: 'client-005',
    entityName: 'Anthropic PBC',
    entityType: 'client',
    overallScore: 20,
    riskLevel: 'Low',
    breakdown: {
      geographic: 15,
      industry: 22,
      ownership: 18,
      compliance: 20,
      adverseMedia: 25,
      sanctions: 8,
    },
    lastAssessed: '2024-12-01T10:00:00Z',
    nextReview: '2025-06-01T10:00:00Z',
    flags: [
      'AI safety company with strong investor backing',
      'Amazon $4B investment requires ongoing monitoring',
    ],
    recommendations: [
      'Continue standard monitoring frequency',
      'Review Amazon partnership structure annually',
      'Monitor for regulatory changes in AI industry',
    ],
  },
  {
    entityId: 'client-006',
    entityName: 'Databricks Inc.',
    entityType: 'client',
    overallScore: 18,
    riskLevel: 'Low',
    breakdown: {
      geographic: 12,
      industry: 20,
      ownership: 15,
      compliance: 18,
      adverseMedia: 20,
      sanctions: 5,
    },
    lastAssessed: '2024-11-15T10:00:00Z',
    nextReview: '2025-05-15T10:00:00Z',
    flags: [],
    recommendations: [
      'Maintain current monitoring frequency',
      'Continue annual compliance reviews',
    ],
  },
  {
    entityId: 'client-007',
    entityName: 'Rivian Automotive, LLC',
    entityType: 'client',
    overallScore: 25,
    riskLevel: 'Low',
    breakdown: {
      geographic: 20,
      industry: 30,
      ownership: 22,
      compliance: 25,
      adverseMedia: 30,
      sanctions: 10,
    },
    lastAssessed: '2024-12-01T10:00:00Z',
    nextReview: '2025-06-01T10:00:00Z',
    flags: [
      'Publicly traded company (NASDAQ: RIVN)',
      'Manufacturing operations require environmental compliance monitoring',
    ],
    recommendations: [
      'Monitor SEC filings and public disclosures',
      'Review environmental compliance annually',
      'Standard monitoring frequency appropriate',
    ],
  },
  {
    entityId: 'client-008',
    entityName: 'Snowflake Inc.',
    entityType: 'client',
    overallScore: 15,
    riskLevel: 'Low',
    breakdown: {
      geographic: 10,
      industry: 18,
      ownership: 12,
      compliance: 15,
      adverseMedia: 18,
      sanctions: 5,
    },
    lastAssessed: '2024-11-01T10:00:00Z',
    nextReview: '2025-05-01T10:00:00Z',
    flags: [],
    recommendations: [
      'Maintain current monitoring frequency',
      'Continue annual compliance reviews',
    ],
  },
  {
    entityId: 'vendor-001',
    entityName: 'Microsoft Corporation',
    entityType: 'vendor',
    overallScore: 12,
    riskLevel: 'Low',
    breakdown: {
      geographic: 8,
      industry: 15,
      ownership: 10,
      compliance: 12,
      adverseMedia: 15,
      sanctions: 5,
    },
    lastAssessed: '2024-12-01T10:00:00Z',
    nextReview: '2025-12-01T10:00:00Z',
    flags: [],
    recommendations: [
      'Verify SOC 2 Type II certification annually',
      'Review data security policies',
      'Standard annual review sufficient',
      'Monitor for changes in cloud service offerings',
    ],
  },
  {
    entityId: 'vendor-002',
    entityName: 'Amazon Web Services (AWS)',
    entityType: 'vendor',
    overallScore: 15,
    riskLevel: 'Low',
    breakdown: {
      geographic: 10,
      industry: 18,
      ownership: 12,
      compliance: 15,
      adverseMedia: 18,
      sanctions: 8,
    },
    lastAssessed: '2024-11-15T10:00:00Z',
    nextReview: '2025-11-15T10:00:00Z',
    flags: [],
    recommendations: [
      'Verify SOC 2 Type II certification annually',
      'Review data security and compliance certifications',
      'Standard annual review sufficient',
      'Monitor for changes in cloud service offerings',
    ],
  },
  {
    entityId: 'vendor-003',
    entityName: 'Salesforce.com, Inc.',
    entityType: 'vendor',
    overallScore: 18,
    riskLevel: 'Low',
    breakdown: {
      geographic: 12,
      industry: 20,
      ownership: 15,
      compliance: 18,
      adverseMedia: 20,
      sanctions: 5,
    },
    lastAssessed: '2024-10-01T10:00:00Z',
    nextReview: '2025-10-01T10:00:00Z',
    flags: [],
    recommendations: [
      'Verify SOC 2 Type II certification annually',
      'Review data security policies',
      'Standard annual review sufficient',
    ],
  },
  {
    entityId: 'vendor-004',
    entityName: 'Oracle Corporation',
    entityType: 'vendor',
    overallScore: 20,
    riskLevel: 'Low',
    breakdown: {
      geographic: 15,
      industry: 22,
      ownership: 18,
      compliance: 20,
      adverseMedia: 22,
      sanctions: 8,
    },
    lastAssessed: '2024-09-15T10:00:00Z',
    nextReview: '2025-09-15T10:00:00Z',
    flags: [],
    recommendations: [
      'Verify database security certifications annually',
      'Review license compliance',
      'Standard annual review sufficient',
    ],
  },
  {
    entityId: 'vendor-005',
    entityName: 'ServiceNow, Inc.',
    entityType: 'vendor',
    overallScore: 16,
    riskLevel: 'Low',
    breakdown: {
      geographic: 12,
      industry: 18,
      ownership: 14,
      compliance: 16,
      adverseMedia: 18,
      sanctions: 5,
    },
    lastAssessed: '2024-11-01T10:00:00Z',
    nextReview: '2025-11-01T10:00:00Z',
    flags: [],
    recommendations: [
      'Verify SOC 2 Type II certification annually',
      'Review workflow automation security',
      'Standard annual review sufficient',
    ],
  },
  {
    entityId: 'vendor-006',
    entityName: 'Deloitte Touche Solutions',
    entityType: 'vendor',
    overallScore: 22,
    riskLevel: 'Low',
    breakdown: {
      geographic: 18,
      industry: 25,
      ownership: 20,
      compliance: 22,
      adverseMedia: 25,
      sanctions: 10,
    },
    lastAssessed: '2024-10-15T10:00:00Z',
    nextReview: '2025-10-15T10:00:00Z',
    flags: [
      'Big Four accounting firm - standard risk profile',
    ],
    recommendations: [
      'Verify professional licenses annually',
      'Review consulting engagement terms',
      'Standard annual review sufficient',
    ],
  },
  {
    entityId: 'vendor-007',
    entityName: 'Bloomberg L.P.',
    entityType: 'vendor',
    overallScore: 18,
    riskLevel: 'Low',
    breakdown: {
      geographic: 15,
      industry: 20,
      ownership: 16,
      compliance: 18,
      adverseMedia: 20,
      sanctions: 12,
    },
    lastAssessed: '2024-12-01T10:00:00Z',
    nextReview: '2025-12-01T10:00:00Z',
    flags: [],
    recommendations: [
      'Verify data license terms annually',
      'Review market data compliance',
      'Standard annual review sufficient',
    ],
  },
  {
    entityId: 'vendor-008',
    entityName: 'Refinitiv (formerly Thomson Reuters)',
    entityType: 'vendor',
    overallScore: 25,
    riskLevel: 'Low',
    breakdown: {
      geographic: 20,
      industry: 28,
      ownership: 22,
      compliance: 25,
      adverseMedia: 28,
      sanctions: 15,
    },
    lastAssessed: '2024-11-15T10:00:00Z',
    nextReview: '2025-11-15T10:00:00Z',
    flags: [
      'Critical vendor for KYC and sanctions screening data',
    ],
    recommendations: [
      'Verify data accuracy and coverage annually',
      'Review sanctions screening data quality',
      'Monitor for changes in data sources',
      'Standard annual review sufficient',
    ],
  },
]
